defaults: &defaults
  cloud_name: <%= ENV['CLOUDINARY_CLOUD'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false


test:
  <<: *defaults

cucumber:
  <<: *defaults

development:
  <<: *defaults

staging:
  <<: *defaults
  enhance_image_tag: true
  static_image_support: true

production:
  <<: *defaults
  enhance_image_tag: true
  static_image_support: true
